name: zenquery
description: "Wrapper around Riverpod for powerful asynchronous state management, server-state utilities and data fetching. Inspired by TanStack Query"
version: 1.0.0

resolution: workspace

homepage: https://github.com/definev/zensuite
repository: https://github.com/definev/zensuite
issue_tracker: https://github.com/definev/zensuite/issues

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  riverpod: ^3.2.0
  flutter_riverpod: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
