name: zenbus
description: A high-performance event bus for Dart/Flutter
version: 1.0.1
repository: https://github.com/definev/zensuite
homepage: https://github.com/definev/zensuite/tree/main/packages/zenbus
issue_tracker: https://github.com/definev/zensuite/issues

resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  alien_signals: ^2.1.2

dev_dependencies:
  lints: ^6.1.0
  vm_service: ^14.3.1
